Lesson4.ArraysAndCycles.
kevalt88/it-academy-java-core pull request #4
Opened 2022-09-20 21:26 UTC by kevalt88

2022-09-21 07:47 UTC, Xini1 requested changes
Не хватает задания, где нужно напечатать звезды количеством, соответствующем числу из массива (для каждого числа на новой строке).

2022-09-21 07:47 UTC, Xini1 commented on scr/main/java/by/it_academy/lesson4/ArraysAndCycles.java
> +        int[] number = new int[]{-2, 1, 5, 8, 9, -5, 4};
Может стоило назвать numbers, потому что в массиве не одно, а несколько чисел

2022-09-21 07:51 UTC, kevalt88 commented
Да, знаю. Вчера не закончил, поэтому закоммитил пока только первое задание.

2022-09-22 15:22 UTC, Xini1 requested changes

2022-09-22 15:22 UTC, Xini1 commented on scr/main/java/by/it_academy/lesson4/ArraysAndCycles2.java
> +                System.out.println("********");
Используй циклы

2022-09-26 06:59 UTC, Xini1 commented
По итогу - 8

2022-09-26 06:59 UTC, merged