Lesson5.
kevalt88/it-academy-java-core pull request #5
Opened 2022-10-01 16:18 UTC by kevalt88

2022-10-03 07:41 UTC, Xini1 requested changes
Еще нужно перенести решения в пакет lesson6

2022-10-03 07:41 UTC, Xini1 commented on scr/main/java/by/it_academy/lesson5/PaymentCard.java
> +    double x = 500;
это поле не нужно

2022-10-03 07:41 UTC, Xini1 commented on scr/main/java/by/it_academy/lesson5/PaymentCard.java
> +        this.balance = x;
ты присваиваешь значение баланса карты всегда 500, независимо от того, что передали в конструктор

2022-10-03 07:41 UTC, Xini1 commented on scr/main/java/by/it_academy/lesson5/PaymentCard.java
> +        if (a > 0)
Не забывай про скобки { } в if

2022-10-03 07:41 UTC, Xini1 commented on scr/main/java/by/it_academy/lesson5/PaymentCard.java
> +            System.out.println(a);
Нужно не печатать баланс, а изменить значение поля

2022-10-03 07:41 UTC, Xini1 commented on scr/main/java/by/it_academy/lesson5/PaymentCard.java
> +        double salary = 1000;
Сумму, на которую нужно пополнить баланс, нужно передавать агрументом в метод

2022-10-03 07:41 UTC, Xini1 commented on scr/main/java/by/it_academy/lesson5/Whistle.java
> +    public void testOfSound() {
по уловию метод должен называться sound

2022-10-05 07:35 UTC, Xini1 commented
Я переименовал пакеты. Не забудь обновить ветку локально у себя в проекте

2022-10-05 09:56 UTC, kevalt88 commented
Спасибо Максим!

2022-10-10 16:23 UTC, Xini1 commented
8

2022-10-10 16:23 UTC, merged